#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul  9 20:46:41 2023

@author: Paul
"""

'''
statistics = branch of mathematics that deals with collection, cleaning, and analysis of data
    
    "What kind of insiights can we gain??"
    
    Descriptive Stats = 
        central tendency = data distribution's central value = average, expected value, mean
        
        dispersion = data distribution's spread = standard deviation, variance, distance from the mean
        
    Inferential STats = 
        population = group of all of the items or events we're studying, usually impractical or impossible to get data
        
                    so we get a sample
        
        Sample = subset of the population selected via a defined method, much easier to obtain, draw conclusions based on the sample
        
    
    
2. Mean and Standard deviation

    mean = central tendency
        sum of the dataset divided by the number of data points 
    
    Standard deviation
        measures the spread or dispersion of the data
        
    Variance = the "average" of the squared differences of the data from the mean
        look up formula for this
    
3. Inferential Statistics
    Linear Regression
        given our data, what is the slope and y-intercept of the line that "best" represents the trend of the data
        use this line-of-best-fit to make predictions
            y = mx + b
            
    least squares linear reression
        pick a line such that the sum of the squared vertical differences is minimal
        falls under field of mathematical optimization problems
        closed-form exact solution exists
    
    correlation coefficient
        measure of strength and linearity of the line-of-best-fit
        pearson correlation coeffecient (PCC) denoted by r
            r > 0 means X correlates positively with Y; r < 0 means X correlates negatively with Y
            |r| === 0 means there is a weak correlation; |r| === 1 means there is a strong correlation
            
    ALWAYS PLOT YOUR DATA
        Anscombe quartet
            demonstrates how radically different data sets can have roughly the same correlation coefficient
    CORRELATION DOES NOT IMPLY CAUSATION!
        total revenue generated by arcades correlates with computer science doctorates awarded in the US
            ...these are completed unrelated but do have a high correlation
            
'''